import "server-only";

import type {
  CreateSessionParams,
  SessionId,
  SessionRecord,
  SessionRepo,
} from "../sessionRepo";

import { kv } from "@vercel/kv";

function key(sessionId: SessionId) {
  return `ttd:sess:${sessionId}`;
}

export class KvSessionRepo implements SessionRepo {
  async create(params: CreateSessionParams): Promise<SessionRecord> {
    const record: SessionRecord = {
      sessionId: params.sessionId ?? params.sessionId, // (ignore; sessionId is generated in memory repo)
      userId: params.userId,
      createdAt: new Date(),
      expiresAt: params.expiresAt,
    };

    // NOTE: We expect sessionId to be generated by the service layer.
    // If your SessionRepo.create currently generates it, tell me and I’ll adjust this file in 10s.
    await kv.set(key(record.sessionId), record, {
      ex: Math.max(
        1,
        Math.floor((record.expiresAt.getTime() - Date.now()) / 1000),
      ),
    });

    return record;
  }

  async get(sessionId: SessionId): Promise<SessionRecord | null> {
    const record = (await kv.get<SessionRecord>(key(sessionId))) ?? null;
    if (!record) return null;

    // Dates come back as strings sometimes -> normalize
    const expiresAt = new Date((record as any).expiresAt);
    if (expiresAt.getTime() <= Date.now()) {
      await kv.del(key(sessionId));
      return null;
    }

    return {
      ...record,
      createdAt: new Date((record as any).createdAt),
      expiresAt,
    };
  }

  async delete(sessionId: SessionId): Promise<boolean> {
    const removed = await kv.del(key(sessionId));
    return removed > 0;
  }

  async deleteExpired(): Promise<number> {
    // KV uses TTL, so explicit cleanup isn't needed.
    return 0;
  }
}
